[Miscellaneous]
; ExitButton Ausblenden fuer Anwender und Abfrage-Fenster fuer Service
ExitButton = TRUE
ExitButtonIndex = 15
ExitButtonAccessLevel = 1
ExitButtonQueryUser = TRUE
EnableRebootDialog = TRUE

[TaskConfiguration]
Task7 = name := jobdh, Timeout := 90000
Task9 = name := oemCS, Timeout := 90000, PreLoad := False, ACCESSLEVEL := 4
Task19 = name := SCounter, Timeout := 40000
Task20 = name := oemframe, cmdLine := "E:\Program Files\DMGplusIT\DMGServiceAgent\DMGWI.exe -ad", WindowName := "DMG-Service Agent", HeaderOnTop := False, PreLoad := True

[StartupConfiguration]
Startup22 = name := vibrab, CmdLine := "", Timeout := 0
Startup23 = name := DncSrv, CmdLine := "-wh -a", Timeout := 0
Startup24 = name := MchnSrv, CmdLine := "-wh", Timeout := 0
Startup25 = name := StrtVBS, CmdLine := "", Timeout := 0
Startup47 = name := runopcua, Timeout := 30000
